### ISSUE TITLE
Let's just use Docusaurus 

### ISSUE THREAD

**Issue by firdavsDev** [vodiylik/djpy#3]
It is just advice bro: Let's use https://docusaurus.io/ ;)

**Comment by vodiylik** [comment]
> It is just advice bro: Let's use https://docusaurus.io/ ;)

Are you ready to contribute?

**Comment by firdavsDev** [comment]
> > It is just advice bro: Let's use https://docusaurus.io/ ;)
> 
> Are you ready to contribute?

Yeah, why not. But I am not a frontend dev sorry.....
